#!/bin/sh

usage()
{
	echo "usage: $0 [--cflags] [--libs] [--version]"
	exit 0
}

cflags=no
libs=no
version=no

test "$1" || usage

while test "$1"; do
	case "$1" in
	--cflags )
		cflags=yes
		;;
	--libs )
		libs=yes
		;;
	--version )
		version=yes
		;;
	* )
		usage
		;;
	esac
	shift
done

test "$cflags" = yes && cat << FOO
-I/usr/local/include/kannel -fcommon -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_LARGE_FILES= -I/usr/include/libxml2 -I/usr/include/postgresql
FOO

test "$libs" = yes && cat << FOO
-L/usr/local/lib/kannel -lgw -lwap -lgwlib -lpq -lrt -lresolv -lm  -lpthread -lxml2 -L/usr/lib/x86_64-linux-gnu 
FOO

test "$version" = yes && cat << FOO
svn-r
FOO

